In [15]:
pip install transformers

In [2]:
from transformers import pipeline

In [3]:
import transformers
print(transformers.__version__)

4.47.0


In [4]:
import librosa  # librosa is a python package for audio and music analysis variety of format such as w mp3 mp4 and like that
import torch  # it is machine learning base library used such as computer vision  and nlp  devloped by meta AI

import IPython.display as display
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer  # w2 vectorizer ctc is supported by the notebook on how to fine tune a speech recogination,  Tokenizer is a conversion a text into meanigful  lexical tokens belonging to categories defined
import numpy as np


In [5]:
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.60k [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.10/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:720: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [14]:
audio, sampling_rate = librosa.load("/content/audio [FDMR.Party].mp3", sr=16000)


In [13]:
audio, sampling_rate

(array([ 3.12145448e-06, -5.34863784e-06, -5.34589890e-06, ...,
        -1.00015804e-01, -1.13373265e-01,  0.00000000e+00], dtype=float32),
 16000)

In [16]:
display.Audio ("/content/audio [FDMR.Party].mp3" , autoplay=True)

In [17]:
input_values = tokenizer(audio, return_tensors  = 'pt').input_values
input_values

tensor([[-0.0010, -0.0010, -0.0010,  ..., -0.4443, -0.5035, -0.0010]])

In [18]:
logits = model (input_values).logits #logits which means non-normalized predections
logits


tensor([[[ 13.5012, -28.7931, -28.5516,  ...,  -7.7374,  -5.7755,  -8.5296],
         [ 13.9161, -29.1879, -28.9518,  ...,  -7.7698,  -5.9498,  -8.5742],
         [ 13.6342, -28.9480, -28.7087,  ...,  -7.7034,  -5.8010,  -8.4969],
         ...,
         [ 14.0630, -29.6732, -29.4453,  ...,  -8.2214,  -7.0351,  -8.4984],
         [ 14.1547, -29.4595, -29.2098,  ...,  -8.0735,  -6.9543,  -8.5607],
         [ 14.1771, -29.3926, -29.1422,  ...,  -7.9988,  -6.9055,  -8.5204]]],
       grad_fn=<ViewBackward0>)

In [19]:
predicted_ids = torch.argmax(logits, dim=-1)


In [20]:
transcription = tokenizer.decode(predicted_ids[0])

In [21]:
transcription

'MISTER RAMPLEASE PICK UP THE HONE MISTER RAMPLEAE PICK UP THE PONE MISTER RAMPLEASE PICK UP THE PONE MISTER RAMPLEASE PICK UP THE PHONE MISTER RAMPLEASE PICK UP THE PONE'